// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.TypeProviders.SDK.Functional.Runtime")>]
[<assembly: AssemblyProductAttribute("FSharp.TypeProviders.SDK.Functional")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FSharp.TypeProviders.SDK.Functional.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.TypeProviders.SDK.Functional.Runtime"
    let [<Literal>] AssemblyProduct = "FSharp.TypeProviders.SDK.Functional"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FSharp.TypeProviders.SDK.Functional."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
